development:
  adapter: postgresql
  database: tripsharing_development
  host: localhost

test:
  adapter: postgresql
  database: tripsharing_test
  host: localhost
  
production:
  adapter: postgresql
  database: tripsharing_production
  host: localhost
